[packages.linux_arch]
paru = [
  "git",
  "mise-bin",
  "neovim-nightly-bin",
  "reflector",
  "wget",
  "fzf",
  "lazygit",
  "github-cli",
  "rustup",
  "ripgrep",
  "fd",
  "bottom",
  "starship",
]
